#!/usr/bin/env bash

#needs to increment on every change!!!
#version: 13

#initialize variables
readonly DEFAULT_DOCKER_IMAGE_REGISTRY="ghcr.io/spring-media"
readonly DEFAULT_DOCKER_IMAGE_NAME=maps-tools
readonly DEFAULT_DOCKER_IMAGE_TAG=latest
readonly DEFAULT_DOCKER_IMAGE="${DEFAULT_DOCKER_IMAGE_REGISTRY}/${DEFAULT_DOCKER_IMAGE_NAME}:${DEFAULT_DOCKER_IMAGE_TAG}"
readonly DEFAULT_DOCKER_USERNAME=k8s
readonly DEFAULT_TEAM_NAMES="red lean mediasites ott apps mds privacywatch kafka hh"
USE_DOCKER_IMAGE=false
DEFAULT_STAGE=$AWS_PROFILE
USE_AWS_VOLUME=true
CREATE_DAEMON_CONTAINER=false
CONTAINER_ATTACH=false
AZURE_LOGIN=false
AZURE_LOGIN_ROLE=Developer
UPDATE=false
USER_NAME=${HOME##*/}
declare -a ADDITIONAL_CONTAINER_ARGS
volumes[0]="-v $HOME/.aws:/home/$DEFAULT_DOCKER_USERNAME/.aws"
volumes[1]="-v $HOME:/home/$USER_NAME"
volumes[2]="-v $HOME/.ssh:/home/$DEFAULT_DOCKER_USERNAME/.ssh"
volumes[3]="-v $HOME/.helm:/home/$DEFAULT_DOCKER_USERNAME/.helm"
volumes[4]="-v $HOME/.kube:/home/$DEFAULT_DOCKER_USERNAME/.kube"

function print_usage() {
  echo
  echo "Usage: $0 [-e] [-v] [-h] [-i]"
  echo '-e: Environment example (AWS_PROFILE NAME: as-spring-mediasites-stage|as-spring-mediasites-prod)'
  echo '-v: DO NOT USE a Docker volume mount for local .aws, .ssh, .helm and .kube configs inside the container.'
  echo '-h: Print this help text'
  echo '-i: Ask for a local Docker image to use'
  echo '-d: create daemon container that runs in the background, so you can use docker exec to connect to'
  echo '-a: attach to daemon container that previously created with -d option'
  echo '-l: test option to login with AZURE AD, default role is Developer, you can also specify default assume role: Admin, Developer, OnlyViewer after parameter, e.g. -l Admin'
  echo '-o: add aditional cmd parameter to docker run/create command, IMPORTANT: use double quotes! you can use this option more than one time, e.g. -o "-p 2222:22" -o "-e DISPLAY=host.docker.internal:0"'
  echo '-u: update maps-tools and docker image (force pull)'
  echo

  exit 0
}

function create_docker_run_command() {
  [ $# -ne 1 ] && echo ❌ No image name given to function \"create_docker_run_command\" && return
  local docker_string=""
  local image_name="$1"
  case true in
    "$CREATE_DAEMON_CONTAINER")
      if [[ $(docker ps -a --format "{{.Names}}" --filter "name=maps-tools") == "maps-tools" ]]
      then
        docker rm -f maps-tools 2>&1 >/dev/null
      fi
      if [[ "${USE_AWS_VOLUME}" == true ]]
      then
        docker_string="docker create --name maps-tools ${volumes[*]} -e \"AZURE_LOGIN_ROLE=$AZURE_LOGIN_ROLE\" -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" -e \"AZURE_LOGIN=$AZURE_LOGIN\" ${ADDITIONAL_CONTAINER_ARGS[@]} --entrypoint \"/init/init_daemon.sh\" $image_name"
      else
        docker_string="docker create --name maps-tools ${volumes[1]} -e \"AZURE_LOGIN_ROLE=$AZURE_LOGIN_ROLE\" -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" -e \"AZURE_LOGIN=$AZURE_LOGIN\" ${ADDITIONAL_CONTAINER_ARGS[@]} --entrypoint \"/init/init_daemon.sh\" $image_name"
      fi
      ;;
    "$CONTAINER_ATTACH")
      if [[ $(docker ps --format "{{.Names}}" --filter "name=maps-tools") == "maps-tools" ]]
      then
        docker_string="docker exec -ti -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" ${ADDITIONAL_CONTAINER_ARGS[@]} maps-tools /usr/bin/bash --login"
      elif [[ $(docker ps -a --format "{{.Names}}" --filter "name=maps-tools") == "maps-tools" ]]
      then
        docker_string="docker start maps-tools; docker exec -ti -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" ${ADDITIONAL_CONTAINER_ARGS[@]} maps-tools /init/init.sh"
      fi
      ;;
    *)
      if [[ "${USE_AWS_VOLUME}" == true ]]
      then
        docker_string="docker run -it --rm ${volumes[*]} -e \"AZURE_LOGIN_ROLE=$AZURE_LOGIN_ROLE\" -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" -e \"AZURE_LOGIN=$AZURE_LOGIN\" ${ADDITIONAL_CONTAINER_ARGS[@]} $image_name"
      else
        docker_string="docker run -it --rm ${volumes[1]} -e \"AZURE_LOGIN_ROLE=$AZURE_LOGIN_ROLE\" -e \"DEFAULT_TEAM_NAMES=$DEFAULT_TEAM_NAMES\" -e \"AWS_PROFILE=$DEFAULT_STAGE\" -e \"AZURE_LOGIN=$AZURE_LOGIN\" ${ADDITIONAL_CONTAINER_ARGS[@]} $image_name"
      fi
      ;;
  esac
  echo "$docker_string"
}

function run_docker_image() {
  local image=${DEFAULT_DOCKER_IMAGE}
  printf "ENVIRONMENT: %s\n\n" "${DEFAULT_STAGE}"
  if [[ "${CREATE_DAEMON_CONTAINER}" == true && "${CONTAINER_ATTACH}" == true ]]
  then
    echo "you cannot use -d and -a Option simultaneously"
    exit 1
  fi
  case true in
    "$USE_DOCKER_IMAGE")
      declare -a docker_images=( $(docker images |grep ${DEFAULT_DOCKER_IMAGE_NAME} |awk '{ print $1 ":" $2 }') )
      if [ ${#docker_images[@]} -eq 0 ]; then echo ❌ Image not found. Run \"make build\" or download image from \"GitHub Package Repository\" !; exit 1; fi
      PS3="Choose the image to run: "
      select docker_image_name in "${docker_images[@]}"; do
        if (( $REPLY >= 1 && $REPLY < (( "${#docker_images[@]}" + 1)) )); then
          local image="${docker_images[(($REPLY - 1))]}"
          local docker_run_command="$(create_docker_run_command "$image")"
          eval $docker_run_command
        else
          echo ❌ Invalid choice && exit 1
        fi
        break
      done
      ;;
    *)
      local docker_run_command="$(create_docker_run_command "$image")"
      eval $docker_run_command
    ;;
  esac
}

function get_script() {
  if [ -f ./maps-tools ]; then
    cp -f ./maps-tools /tmp/maps-tools
  else
    curl -s https://raw.githubusercontent.com/spring-media/maps-tools-install/main/maps-tools >/tmp/maps-tools
  fi
  retVal=$?
  if [ $retVal -ne 0 ]; then
    echo "Error getting version of maps-tools"
    exit $retVal
  fi
}

function install_script() {
  if [ -f /tmp/maps-tools ]; then
    cp -f /tmp/maps-tools /usr/local/bin/maps-tools >/dev/null || sudo cp -f /tmp/maps-tools /usr/local/bin/maps-tools
    chmod 755 /usr/local/bin/maps-tools >/dev/null || sudo chmod 755 /usr/local/bin/maps-tools
  else
    echo "no version of maps-tools found for installation"
    exit 1
  fi
}

function check_for_updates() {
  if [ -f /tmp/maps-tools ]; then
    local version=$(grep -m 1 "#version:" /usr/local/bin/maps-tools | awk '{print $2}')
    local new_version=$(grep -m 1 "#version:" /tmp/maps-tools | awk '{print $2}')
    if [ ${version} -lt ${new_version} ]; then
      echo "upgrading maps-tools to version ${new_version}"
      install_script
    else
      echo "no upgrade available for maps-tools"
    fi
  else
    echo "no version of maps-tools found for installation"
    exit 1
  fi
}

function cleanup_tmp() {
  if [ -f /tmp/maps-tools ]; then
    rm -f /tmp/maps-tools
  fi
}

function docker_pull() {
  docker pull ${DEFAULT_DOCKER_IMAGE}
}

function getopts_get_optional_argument() {
  eval next_token=\${$OPTIND}
  if [[ -n $next_token && $next_token != -* ]]; then
    OPTIND=$((OPTIND + 1))
    OPTARG=$next_token
  else
    OPTARG=""
  fi
}

# Parse flags
while getopts "b:o:he:ivdaul" argument; do
  case "${argument}" in
    b)
      # Will be eventually used for additional BUILD ARGs later. Currently, the only BUILD ARG is directly
      # handled in "create_docker_run_command"
      echo 🛠️ TODO !
      ;;
    e)
      DEFAULT_STAGE="${OPTARG}"
      ;;
    v)
      USE_AWS_VOLUME=false
      ;;
    i)
      USE_DOCKER_IMAGE=true
      ;;
    d)
      CREATE_DAEMON_CONTAINER=true
      ;;
    a)
      CONTAINER_ATTACH=true
      ;;
    l)
      getopts_get_optional_argument $@
      AZURE_LOGIN_ROLE=${OPTARG}
      arch=$(uname -m)
      if [[ "$arch" == "amd64" || "$arch" == "x86_64" ]]; then
        AZURE_LOGIN=true;
      else
        echo "╔════════════════════════════════════════════════════════════════════╗"
        echo "║⚠️ CPU ARCHITECTURE NOT SUPPORTED FOR AZURE LOGIN! USING ADFS INSTEAD║"
        echo "╚════════════════════════════════════════════════════════════════════╝"
      fi
      ;;
    u)
      UPDATE=true
      ;;
    o)
      ADDITIONAL_CONTAINER_ARGS+=("$OPTARG")
      ;;
    h | ? | *)
      print_usage
      ;;
  esac
done
shift $((OPTIND - 1))

#self installation or upgrade
if [ ! -x /usr/local/bin/maps-tools ]; then
  echo "installing maps-tools to /usr/local/bin"
  echo ""

  get_script
  install_script
  cleanup_tmp

  echo 'add /usr/local/bin to your $PATH environment variable'
  echo 'for example:'
  echo ''
  echo 'bash:'
  echo 'echo export PATH="/usr/local/bin:\$PATH" >> ${HOME}/.bashrc && source ${HOME}/.bashrc'
  echo 'zsh:'
  echo 'echo export PATH="/usr/local/bin:\$PATH" >> ${HOME}/.zshrc && source ${HOME}/.zshrc'
  echo ''
  exit 0
elif [ -x /usr/local/bin/maps-tools ] && [ "$UPDATE" = true ]; then
  get_script
  check_for_updates
  cleanup_tmp
  docker_pull
  exit 0
elif [ -x /usr/local/bin/maps-tools ] && [ "${0##*/}" != "maps-tools" ]; then
  get_script
  check_for_updates
  cleanup_tmp
  docker_pull
  exit 0
fi

#check docker is installed
if [ ! -d "/Applications/Docker.app" ]; then
  echo "Please Install Docker Desktop"
  exit 1
fi

#check docker is running
(pgrep -x docker > /dev/null && echo "Docker is running" )|| (echo "Starting Docker" && open /Applications/Docker.app && sleep 20)

# Call function to obtain the proper call to docker run
run_docker_image
